services:
  piston:
    container_name: devsync-piston
    image: ghcr.io/engineer-man/piston
    privileged: true
    volumes:
      - ./piston-data:/piston
    networks:
      - DevSync
    ports:
      - "2000:2000"

  server:
    container_name: devsync-server
    build:
      context: ./server
      dockerfile: Dockerfile
      target: runner
    environment:
      - PORT=5001
      - PISTON_API_URL=http://piston:2000/api/v2
    volumes:
      - ./server:/app
      - /build/node_modules
    networks:
      - DevSync
    ports:
      - "5001:5001"
    depends_on:
      - piston

  client:
    container_name: devsync-client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./client:/app
      - /build/node_modules
    networks:
      - DevSync
    ports:
      - "5173:5173"
    depends_on:
      - server

networks:
  DevSync:
    driver: bridge
